apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraform.fullname" . }}
  labels:
{{ include "terraform.labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/targets: openstack
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "terraform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
