name: Linting the repository

on: [push, pull_request]

env:
  UPPER_CONSTRAINTS: "https://raw.githubusercontent.com/sapcc/requirements/stable/2025.1-m3/upper-constraints.txt"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        set -xe
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r test-requirements.txt -c $UPPER_CONSTRAINTS
    - name: Analysing the code with pylint
      run: |
        tools/coding-checks.sh --pylint
        flake8 ./octavia_f5 --count --ignore H104,W504 --enable-extensions H106,H203,H204,H205,H904 --max-line-length=127 --statistics
